FROM php:8.2-apache

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y curl git zip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && a2enmod rewrite

RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/web|' /etc/apache2/sites-available/000-default.conf

RUN a2ensite 000-default.conf

COPY app/ /var/www/html

EXPOSE 85

CMD ["apache2-foreground"]
