FROM yiisoftware/yii2-php:8.2-apache

COPY advanced/ /app
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y curl git zip \
    && rm -rf /var/lib/apt/lists/*
    
RUN sed -i -e 's|/app/web|/app/backend/web|g' /etc/apache2/sites-available/000-default.conf
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get update && apt-get upgrade -y
RUN docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && a2enmod rewrite

EXPOSE 82